// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tidhpstnldsormloeatk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZGhwc3RubGRzb3JtbG9lYXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTgxODIsImV4cCI6MjA2MTA3NDE4Mn0.wGx2iPBp79AErZtVUpgD7wktBU5LGzK2d7AilxoLFZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);